### ISSUE TITLE
Purpose of Booted()?

### ISSUE THREAD

**Issue by jack-chung** [julienschmidt/systemd#1]
Hello,

Is Booted() supposed to help determine if the go application is launched by systemd?
For me it's returning true even when I run the go app directly without systemd, as long as the folder /run/systemd/system is there. That folder seems to always exists on my Ubuntu (as an empty folder).

**Comment by julienschmidt** [comment]
See https://godoc.org/github.com/julienschmidt/systemd#Booted.
Its a port of https://www.freedesktop.org/software/systemd/man/sd_booted.html
